apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ugclive-ingress
  namespace: ugclive-bid
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: app.ugclivebid.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ugclive-web
                port:
                  number: 80
    - host: api.ugclivebid.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ugclive-api
                port:
                  number: 80

